### ISSUE TITLE
Add option to specify settings filepath in env var

### ISSUE THREAD

**Issue by christoffer00** [EdrisT/SublimeLinter-contrib-Powershell#1]
Hi,

I like this plugin but one thing I found a bit annoying is that I have to have my PSScriptAnalyzer settings file in the project root (or set a global variable which I don't want to because that will not be project specific).

I forked the repository and added the option to set the path in an environment variable, that way I can specify the path in the SublimeLinter settings in my .sublime-project file. Here is the link to the commit https://github.com/christoffer88/SublimeLinter-contrib-Powershell/commit/6a46c1eab396f8aa0b073bcc471046d6e5e55b78.

Do you think this is a good idea, maybe you want to pull it into the main repository?

**Comment by EdrisT** [comment]
Sure thing, it's a good idea.

**Comment by EdrisT** [comment]
The new update (1.0.8) is on packagecontrol.io now.
